package com.flowpay.app
import android.content.*;import android.net.Uri;import android.os.Bundle
import androidx.activity.ComponentActivity;import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*;import androidx.compose.foundation.lazy.*;import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions;import androidx.compose.material.icons.Icons;import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.Modifier;import androidx.compose.ui.graphics.Color;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.text.input.KeyboardType;import androidx.compose.ui.unit.dp;import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage;import kotlinx.coroutines.*;import org.json.*;import java.net.*;import androidx.work.*

data class Wish(val id:String,val name:String,val url:String,val image:String,val price:Double,val history:List<Double>)
data class Pay(val name:String,val amount:Double)
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);if(android.os.Build.VERSION.SDK_INT>=33)requestPermissions(arrayOf(android.Manifest.permission.POST_NOTIFICATIONS),7);PriceWorker.schedule(this);setContent{App(this)}}}
class Store(c:Context){private val p=c.getSharedPreferences("flowpay",0)
 fun wishes():List<Wish>{val a=JSONArray(p.getString("w","[]"));return(0 until a.length()).map{val o=a.getJSONObject(it);val h=o.getJSONArray("h");Wish(o.getString("id"),o.getString("n"),o.getString("u"),o.getString("i"),o.getDouble("p"),(0 until h.length()).map{x->h.getDouble(x)})}}
 fun save(x:List<Wish>){p.edit().putString("w",JSONArray(x.map{JSONObject().put("id",it.id).put("n",it.name).put("u",it.url).put("i",it.image).put("p",it.price).put("h",JSONArray(it.history))}).toString()).apply()}
 fun pays():List<Pay>{val a=JSONArray(p.getString("pay","[]"));return(0 until a.length()).map{val o=a.getJSONObject(it);Pay(o.getString("n"),o.getDouble("a"))}}
 fun savePays(x:List<Pay>){p.edit().putString("pay",JSONArray(x.map{JSONObject().put("n",it.name).put("a",it.amount)}).toString()).apply()}}
suspend fun product(link:String)=withContext(Dispatchers.IO){val c=URL(link).openConnection()as HttpURLConnection;c.setRequestProperty("User-Agent","Mozilla/5.0 Android");val s=c.inputStream.bufferedReader().readText()
 fun meta(k:String)=Regex("""<meta[^>]+(?:property|name)=["']$k["'][^>]+content=["']([^"']+)""",RegexOption.IGNORE_CASE).find(s)?.groupValues?.get(1)?:""
 val raw=meta("product:price:amount").ifBlank{Regex("""\"price\"\s*:\s*[\"']?([0-9.]+)""").find(s)?.groupValues?.get(1)?:"0"};val p=raw.toDoubleOrNull()?:0.0
 Wish(System.currentTimeMillis().toString(),meta("og:title").ifBlank{"Новий товар"},link,meta("og:image"),p,listOf(p))}
suspend fun usd()=withContext(Dispatchers.IO){val a=JSONArray(URL("https://api.monobank.ua/bank/currency").readText());(0 until a.length()).map{a.getJSONObject(it)}.first{it.getInt("currencyCodeA")==840&&it.getInt("currencyCodeB")==980}.optDouble("rateSell")}
val Lime=Color(0xffcbfb60);val Bg=Color(0xff030601);val Panel=Color(0xff1c1c1c)
@Composable fun App(c:Context){val s=remember{Store(c)};var tab by remember{mutableIntStateOf(0)};var w by remember{mutableStateOf(s.wishes())};var p by remember{mutableStateOf(s.pays())}
 LaunchedEffect(Unit){if(w.isEmpty())runCatching{product("https://prom.ua/ua/p2522203669-muzhskie-krossovki-asics.html")}.onSuccess{w=listOf(it);s.save(w)}}
 MaterialTheme(colorScheme=darkColorScheme(primary=Lime,background=Bg,surface=Panel)){Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Panel){listOf(Icons.Default.Favorite to "Вішліст",Icons.Default.Calculate to "Калькулятор",Icons.Default.Receipt to "Платежі",Icons.Default.Settings to "Ще").forEachIndexed{i,x->NavigationBarItem(tab==i,{tab=i},{Icon(x.first,null)},label={Text(x.second)})}}}){q->Box(Modifier.padding(q)){when(tab){0->Wishlist(w,{w=it;s.save(it)},c);1->Calc();2->Pays(p,{p=it;s.savePays(it)});else->About()}}}}}
@Composable fun Head(a:String,b:String){Column(Modifier.padding(20.dp)){Text(a,color=Lime,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(b,fontSize=36.sp,fontWeight=FontWeight.Black)}}
@Composable fun Wishlist(ws:List<Wish>,save:(List<Wish>)->Unit,c:Context){var show by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();LazyColumn(contentPadding=PaddingValues(bottom=80.dp)){item{Head("FLOWPAY","Мої бажання");Button({show=true},Modifier.padding(horizontal=20.dp).fillMaxWidth(),shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.Add,null);Text(" Додати посилання")}};items(ws){x->Card(Modifier.padding(10.dp).fillMaxWidth(),shape=RoundedCornerShape(24.dp)){AsyncImage(x.image,x.name,Modifier.fillMaxWidth().height(230.dp));Column(Modifier.padding(18.dp)){Text(x.name,fontSize=20.sp,fontWeight=FontWeight.Bold);Text("${"%,.0f".format(x.price)} ₴",fontSize=28.sp,color=Lime,fontWeight=FontWeight.Black);Text("Історія: "+x.history.joinToString(" → "){"%,.0f".format(it)},fontSize=11.sp);Row{TextButton({c.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(x.url)))}){Text("До магазину ↗")};Spacer(Modifier.weight(1f));IconButton({save(ws-x)}){Icon(Icons.Default.Delete,null)}}}}}}
 if(show){var link by remember{mutableStateOf("")};AlertDialog({show=false},{Button({scope.launch{runCatching{product(link)}.onSuccess{save(ws+it);show=false}}},enabled=link.startsWith("http")){Text("Додати")}},title={Text("Посилання на товар")},text={OutlinedTextField(link,{link=it},label={Text("Prom.ua або інший магазин")})},dismissButton={TextButton({show=false}){Text("Скасувати")}})}}
@Composable fun Field(n:String,v:String,set:(String)->Unit)=OutlinedTextField(v,set,Modifier.fillMaxWidth().padding(bottom=12.dp),label={Text(n)},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal))
@Composable fun Calc(){var av by remember{mutableStateOf("")};var sal by remember{mutableStateOf("")};var rate by remember{mutableDoubleStateOf(0.0)};val sc=rememberCoroutineScope();Column{Head("ПЛАНУВАННЯ","Калькулятор");Column(Modifier.padding(20.dp)){Field("Аванс",av){av=it};Field("Основна зарплата",sal){sal=it};Text("Разом: ${"%,.0f".format((av.toDoubleOrNull()?:0.0)+(sal.toDoubleOrNull()?:0.0))} ₴",fontSize=24.sp,color=Lime);Button({sc.launch{rate=runCatching{usd()}.getOrDefault(0.0)}}){Text("Курс Monobank")};if(rate>0)Text("1 USD = $rate ₴",fontSize=20.sp)}}}
@Composable fun Pays(xs:List<Pay>,save:(List<Pay>)->Unit){var n by remember{mutableStateOf("")};var a by remember{mutableStateOf("")};LazyColumn{item{Head("ЩОМІСЯЦЯ","Регулярні платежі");Column(Modifier.padding(20.dp)){OutlinedTextField(n,{n=it},Modifier.fillMaxWidth(),label={Text("Назва")});Field("Сума",a){a=it};Button({a.toDoubleOrNull()?.let{save(xs+Pay(n,it));n="";a=""}},Modifier.fillMaxWidth()){Text("Додати")};Text("Разом: ${"%,.0f".format(xs.sumOf{it.amount})} ₴",Modifier.padding(top=18.dp),fontSize=24.sp,color=Lime)}};items(xs){x->ListItem(headlineContent={Text(x.name)},supportingContent={Text("${x.amount} ₴")},trailingContent={IconButton({save(xs-x)}){Icon(Icons.Default.Delete,null)}})}}}
@Composable fun About(){Column{Head("FLOWPAY","Налаштування");Text("Дані зберігаються на телефоні. Ключі не вшиваються в APK.",Modifier.padding(20.dp))}}
